######################################################################
# Arweave Ansible Tasks, Fedora 39 compatible
######################################################################

- name: Update DNF packages repositories
  ansible.builtin.dnf:
    update_cache: yes

- name: Install Arweave package dependencies
  ansible.builtin.dnf:
    update_cache: yes
    state: latest
    pkg: '{{ packages }}'
  vars:
      package: '{{ __arweave_os["x86_64"]["fedora"]["39"]["packages"] }}'