######################################################################
# Arweave Ansible Tasks, Ubuntu 20.04 compatible
######################################################################
- name: Update APT packages repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Arweave package dependencies
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg: '{{ packages }}'
  vars:
      packages: '{{ __arweave_os["x86_64"]["ubuntu"]["20.04"]["packages"] }}'
