######################################################################
# Arweave Ansible Tasks, Ubuntu 22.04 compatible
######################################################################

- name: Update APT packages repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Arweave package dependencies
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg:
      - erlang
      - rebar3
      - libssl-dev
      - libgmp-dev
      - libsqlite3-dev
      - libsqlite3-dev
      - make
      - cmake
      - gcc
      - g++
      - git

