######################################################################
# Arweave Ansible Tasks, Debian 10 Compatible
######################################################################
- name: Update APT packages repositories
  ansible.builtin.apt:
    update_cache: yes

- name: Install Arweave package dependencies
  ansible.builtin.apt:
    update_cache: yes
    state: latest
    pkg: '{{ packages }}'
  vars:
      packages: '{{ __arweave_os["x86_64"]["debian"]["10"]["packages"] }}'
